sudo: false
language: node_js
notifications:
  email: false
node_js:
  - lts/*
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run semantic-release
